config/routes.rb
Benfeitor::Application.routes.draw do
  # scope :constraints => lambda{|request| request.cookies.key?("remember_token") } do
  #   root :to => "users#feed"
  # end    

  root :to => "pages#home"

  resources :authors, :path => "pensadores" do
    member do
      get :fans, path: "fas"
      get :idols, path: "idolos"
      get :users, path: "usuarios"
      get :tags, path: "temas"
      get :favourites, path: "favoritas"
      get :origins, path: "origens"
      get :books, path: "livros"
      get :songs, path: "musicas"
      get :poems, path: "poemas"
      get :films, path: "filmes"
      get :others, path: "outras"
      get :subscriptions, :autocomplete
    end
  end

  resources :users, path: "usuarios" do
    member do
      get :feed, path: "mural"
      get :following, path: "seguindo"
      get :followers, path: "seguidores"
      get :idols, path: "idolos"
      get :fans, path: "fas"
      get :tags, path: "temas"
      get :authors, path: "pensadores"
      get :favourites, path: "favoritas"
      get :origins, path: "origens"
      get :books, path: "livros"
      get :songs, path: "musicas"
      get :poems, path: "poemas"
      get :films, path: "filmes"
      get :others, path: "outras"
      get :favoritadas
      get :proprias
      get :twitter
    end
  end

  resources :tags, path: "temas" do
    member do
      get :microposts, path: "raspas"
      get :users, path: "usuarios"
      get :authors, path: "pensadores"
      get :autocomplete
    end
  end

  resources :taggins do
    member do
      get :tags, path: "temas"
      get :microposts, path: "raspas"
      get :users, path: "usuarios"
    end
  end

  resources :microposts, path: "raspas" do
    member do
      get :favouriters, path: "favoritaram"
    end
  end

  resources :favourites, path: "favoritas" do
    member do
      get :criar
    end
  end

  resources :origins, path: "origens" do

    member do
      get :fans, path: "fas"
      get :idols, path: "idolos"
      get :users, path: "usuarios"
      get :authors, path: "pensadores"
      get :tags, path: "temas"
      get :autocomplete
    end
  end

  resources :books, path: "livros"
  resources :poems, path: "poemas"
  resources :songs, path: "musicas"
  resources :films, path: "filmes"
  resources :others, path: "outras"
  
  resources :sessions, only: [:new, :create, :authenticate, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :subscriptions, only: [:create, :destroy]
  
  get '/signup',  to: 'users#new'
  get '/signin',  to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy'
  get '/home',   to: 'pages#home'
  get '/about',   to: 'pages#about'
  get 'contact' => 'contact#new'
  post 'contact' => 'contact#create'
  get '/auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get '/search', to: "search#index"
  get '/mosaico', to: "pages#mosaico"
  get '/top', to: "pages#top"
  get '/random', to: "microposts#random"
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def index
  	@title = "busca por #{(params[:query])}"
    @tags = Tag.search(params[:query])
    @authors = Author.search(params[:query])
    @users = User.search(params[:query])
    @microposts = Micropost.search(params[:query])
    @origins = Origin.search(params[:query])
    @new_micropost = Micropost.new
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/index.html.erb
<% if @tags.empty? %>
	<div class= "title">
		<p class= "p_search">nenhum tema encontrado</p><%= link_to "explorar temas", tags_path %>
	</div>
<% else %>
	<div class= "title">
		<p class= "p_search">encontramos <%= pluralize @tags.count, "tema" %></p>
		<%= link_to "explorar + temas", tags_path %>
	</div>
	<div class= "home">
		<div class= "tag_word">
			<% @tags.each do |tag| %>
				<div class= "tag_index">
			  		<%= link_to tag.name, tag, class: "but round" %><p class= "p_tags">x <%= tag.taggings.count %></p>
				</div>  	
		  	<% end %>
		</div>
	</div>
<% end %>
<% if @authors.empty? %>
	<div class= "title">
		<p class= "p_search">nenhum pensador encontrado</p>
		<%= link_to "| explorar pensadores", authors_path %>
		<%= link_to "criar perfil para #{(params[:query].titlecase)} ", new_author_path %>
	</div>
<% else %>
	<div class= "title">
		<p class= "p_search">encontramos <%= @authors.count %> pensadores</p>
		<%= link_to "explorar + pensadores", authors_path %>
	</div>
	<div class= "home">
		<ul class="users">
			<%= render @authors %>
		</ul>
	</div>
<% end %>
<% if @users.empty? %>
	<div class= "title">
		<p class= "p_search">nenhum usuário encontrado</p>
		<%= link_to "explorar usuários", users_path %>
	</div>
<% else %>
	<div class= "title">
		<p class= "p_search">encontramos <%= pluralize @users.count, "usuário" %></p>
		<%= link_to "explorar + usuários", users_path %>
	</div>
	<div class= "home">
		<ul class="users">
			<%= render @users %>
		</ul>
	</div>
<% end %>
<% if @origins.empty? %>
	<div class= "title">
		<p class= "p_search">nenhuma origem encontrada</p>
		<%= link_to "| explorar origens", origins_path %>
		<%= link_to "criar página para #{(params[:query].titlecase)} ", new_origin_path %>
	</div>
<% else %>
	<div class= "title">
		<p class= "p_search">encontramos <%= pluralize @origins.count, "fonte" %></p>
		<%= link_to "explorar + origens", origins_path %>
	</div>
	<div class= "home">
		<ul class="users">
			<%= render @origins %>
		</ul>
	</div>
<% end %>
<% if @microposts.empty? %>
	<div class= "title">
		<p class= "p_search">nenhuma raspa encontrada</p>
		<%= link_to "explorar raspas", microposts_path %>
	</div>
<% else %>
	<div class= "title">
		<p class= "p_search">encontramos <%= pluralize @microposts.count, "raspa" %></p>
		<%= link_to "explorar + raspas", microposts_path %>
	</div>
	<div class= "home">
		<br>
		<ul class="users">
			<%= render @microposts %>
		</ul>
	</div>
<% end %>