config/routes.rb
Benfeitor::Application.routes.draw do
  # scope :constraints => lambda{|request| request.cookies.key?("remember_token") } do
  #   root :to => "users#feed"
  # end    

  root :to => "pages#home"

  resources :authors, :path => "pensadores" do
    member do
      get :fans, path: "fas"
      get :idols, path: "idolos"
      get :users, path: "usuarios"
      get :tags, path: "temas"
      get :favourites, path: "favoritas"
      get :origins, path: "origens"
      get :books, path: "livros"
      get :songs, path: "musicas"
      get :poems, path: "poemas"
      get :films, path: "filmes"
      get :others, path: "outras"
      get :subscriptions, :autocomplete
    end
  end

  resources :users, path: "usuarios" do
    member do
      get :feed, path: "mural"
      get :following, path: "seguindo"
      get :followers, path: "seguidores"
      get :idols, path: "idolos"
      get :fans, path: "fas"
      get :tags, path: "temas"
      get :authors, path: "pensadores"
      get :favourites, path: "favoritas"
      get :origins, path: "origens"
      get :books, path: "livros"
      get :songs, path: "musicas"
      get :poems, path: "poemas"
      get :films, path: "filmes"
      get :others, path: "outras"
      get :favoritadas
      get :proprias
      get :twitter
    end
  end

  resources :tags, path: "temas" do
    member do
      get :microposts, path: "raspas"
      get :users, path: "usuarios"
      get :authors, path: "pensadores"
      get :autocomplete
    end
  end

  resources :taggins do
    member do
      get :tags, path: "temas"
      get :microposts, path: "raspas"
      get :users, path: "usuarios"
    end
  end

  resources :microposts, path: "raspas" do
    member do
      get :favouriters, path: "favoritaram"
    end
  end

  resources :favourites, path: "favoritas" do
    member do
      get :criar
    end
  end

  resources :origins, path: "origens" do

    member do
      get :fans, path: "fas"
      get :idols, path: "idolos"
      get :users, path: "usuarios"
      get :authors, path: "pensadores"
      get :tags, path: "temas"
      get :autocomplete
    end
  end

  resources :books, path: "livros"
  resources :poems, path: "poemas"
  resources :songs, path: "musicas"
  resources :films, path: "filmes"
  resources :others, path: "outras"
  
  resources :sessions, only: [:new, :create, :authenticate, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :subscriptions, only: [:create, :destroy]
  
  get '/signup',  to: 'users#new'
  get '/signin',  to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy'
  get '/home',   to: 'pages#home'
  get '/about',   to: 'pages#about'
  get 'contact' => 'contact#new'
  post 'contact' => 'contact#create'
  get '/auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get '/search', to: "search#index"
  get '/mosaico', to: "pages#mosaico"
  get '/top', to: "pages#top"
  get '/random', to: "microposts#random"
end

app/models/origin.rb
class Origin < ActiveRecord::Base
	attr_accessible :name, :date, :image, :info, :content, :author_id, :user_id, :author_name, :link, :type
  attr_accessor :author_name
  before_save :assign_author, :assign_origin, :normalize, :normalize_link
  before_create :titlelize

  mount_uploader :image, ImageUploader

  belongs_to :author
  belongs_to :user
	has_many :microposts, order: "microposts.created_at DESC"
  has_many :authors, -> { order("authors.created_at DESC") }, through: :microposts

  has_many :users, -> { order("users.created_at DESC") }, through: :microposts

  has_many :tags, -> { order("tags.created_at DESC") }, through: :microposts

  validates :name,  presence: true,
            	      length: { maximum: 50 },
                    uniqueness: { case_sensitive: false }

  validates :user_id,  presence: true

  include PgSearch
  pg_search_scope :search, against: [:name, :type],
    using: {tsearch: {prefix: true, dictionary: "portuguese"}},
    associated_against: {microposts: :content, authors: :name},
    ignoring: :accents  

  def normalize
    if content
      self.content = content.gsub(/\n\r/, " ")
    end  
  end

  def normalize_link
    if link
      self.link = link.gsub("watch?v=", "embed/").gsub("http://www", "https://www")
    end  
  end

  def self.text_search(query)
    if query.present?
      search(query)
    else
      scoped
    end
  end

  def titlelize
    if name
      self.name = name.titlecase
    end
  end

  def assign_origin
    if type.blank?
      self.type = 'Other'
    end
  end

  def assign_author
    if author_name
      author = Author.find_or_create_by_name(author_name)
      self.author_id = author ? author.id : 0
    end
  end
end

# def self.inherited(child)
#   child.instance_eval do
#     def model_name
#       Origin.model_name
#     end
#   end
#   super
# end
  
class Book < Origin
end

class Poem < Origin
end

class Song < Origin
end

class Film < Origin
end

class Other < Origin
end

app/controllers/origins_controller.rb
# encoding:   utf-8
class OriginsController < ApplicationController
  before_filter :authenticate, only: [:create, :destroy, :edit]
  before_filter :authorized_user, only: [:edit, :update, :destroy]

  def index
    @title = "Pensamentos e Frases de livros, músicas, poemas e filmes"
    @origins = eval("#{params[:controller].classify}.paginate(page: params[:page], order: :name)")
    # @origins = params[:type].constantize.all
    # @origins = Origin.scoped(order: :name)
    # @origins = origin.paginate(:page => params[:page])
    @new_micropost = Micropost.new
    @tags = Tag.all
  end

  def autocomplete
    @origins = Origin.order(:name).search("%#{params[:term]}%")
    render json: @origins.map(&:name) 
  end

  def show
      @origin = Origin.find(params[:id])
      @microposts = @origin.microposts.paginate(page: params[:page])
      @users = @origin.users.scoped
      @origin_user = @origin.user
      @user_origins = @origin_user.origins.all if @origin_user
      @tags = @origin.tags.scoped
      @origins = Origin.scoped
      @author = @origin.author
      @author_origins = @author.origins.all if @author
      @books = Book.scoped
      @songs = Song.scoped
      @poems = Poem.scoped
      @films = Film.scoped
        # fresh_when etag: [@origin, @microposts], public: true
      @new_micropost = Micropost.new
      @title = "#{@origin.name} - #{@origin.author.name if @origin.author}#{@origin.user.name if !@origin.author}"
  end
  
  def new
    @title = "nova origem"
    @origin = Origin.new
    @new_micropost = Micropost.new
  end

  def create
    # @origin = Origin.new(params[:origin])
    origin = current_user.origins.build(params[:origin])
    if origin.save
      if origin.author
        redirect_to origin
        flash[:success] = "Você adicionou um material de #{origin.author.name}! Obrigado."
      else
        redirect_to origin
        flash[:success] = "Adoramos ver material de sua própria autoria! Obrigado."
      end
    else
      redirect_to :back, notice: origin.errors.full_messages 
      # @title = "nova origem"
      # render 'new'
    end
  end
  
  def edit
    @title = "editar origem"
    @origin = Origin.find(params[:id])
    @new_micropost = Micropost.new
  end

  def update
    @new_micropost = Micropost.new
  	@origin = Origin.find(params[:id])
		@origin.attributes = params[:origin]
    if @origin.content_changed?
	  	@origin.update_attributes(user_id: current_user.id)
	  end
    if @origin.info_changed?
      @origin.update_attributes(user_id: current_user.id)
    end
    if @origin.save
      flash[:success] = "Origem atualizada com sucesso."
      redirect_to @origin
    else
      @title = "editar"
      render 'edit'
    end
  end

  def destroy
    Origin.find(params[:id]).destroy
    flash[:success] = "A origem foi removida com sucesso."
    redirect_to root_path
  end

  def users
    @origin = Origin.find(params[:id])
    @users = @origin.users.all(order: 'users.created_at DESC')
    @new_micropost = Micropost.new
    @origins = Origin.all
    @title = "citaram #{@origin.name}"
    render 'show_users'
  end
    
 	private

  def authorized_user
    @origin = Origin.find(params[:id])
  	if @origin.author_id.blank?
    	@origin = current_user.origins.find_by_id(params[:id])
    	redirect_to root_path if @origin.nil?
  	end
  end
end

app/views/origins/_form.html.erb
<%#= form_for @origin, html: { multipart: true } do |f| %>
<%#= form_for @origin, url: { controller: 'origins', action: 'create' }, as: :origin do |f| %>
<%= form_for([@origin.becomes(Origin)]) do |f| %>
  <% f.object = @origin.becomes(@origin.class) %>
  <%= render 'shared/error_messages', object: f.object %>  
  <div class="cartela round relative">
    <div class= "cartela_corner round">
      <div class= "board_avatar">
          <%= image_tag @origin.image_url(:regular).to_s %>
          <%= f.file_field :image, class: "round" %>
      </div> 
    </div>
    <div class= "board_avatar">
      <div class= "field">
        <div class= "radio">
          <div class= "radio_type">
            <%= f.radio_button :type, 'Book', class: 'book_radio', title: 'livro' %>
            <%= f.label :type, "livro", value: 'Book' %><br />
          </div>  
          <div class= "radio_type">
            <%= f.radio_button :type, 'Poem', class: 'poem_radio', title: 'poema' %>
            <%= f.label :type, "poema", value: 'Poem' %><br />
          </div>
          <div class= "radio_type">
            <%= f.radio_button :type, 'Song', class: 'song_radio', title: 'música' %>
            <%= f.label :type, "música", value: 'Song' %><br />
          </div>  
          <div class= "radio_type">
            <%= f.radio_button :type, 'Film', class: 'film_radio', title: 'filme' %>
            <%= f.label :type, "filme", value: 'Film' %><br />
          </div>
          <div class= "radio_type">
            <%= f.radio_button :type, 'Other', class: 'other_radio', title: 'outras origens' %>
            <%= f.label :type, "outros", value: 'Other' %><br />
          </div>  
        </div>  
        <%= f.text_field :name, placeholder: "nome da origem", class: "round field_info" %>
        <%= f.text_field :author_name, value: "#{@origin.author.name if @origin.author}", data: {autocomplete_source: autocomplete_author_path(current_user)}, placeholder: "pensador", class: "tt round field_info", title: "caso esta origem seja de sua própria autoria, deixe este campo em branco" %>
        <%= f.date_select :date, :start_year => DateTime.now.year, :end_year => DateTime.now.year - 200, prompt: "data de lançamento", class: "round field_info" %>
        <%#= select_year Date.today, start_year: Time.now.year, :end_year => Time.now.year - 200, field_name: :date, prefix: :origin  %>
        <%#= f.select :type, [Book.name, Song.name], prompt: 'tipo da origem', placeholder: "tipo da fonte", class: "round" %>
      </div>
    </div>
    <div>
      <%= f.text_area :info, maxlength: 680, placeholder: "breve descrição de #{@origin.name}", 
      class: "round", id: "origin_info" %>
      <%= f.text_field :link, placeholder: "youtube url", class: "round" %>
    </div>
    <div class= "count_info">
      <div id= "count_bio">680</div>
    </div>
  </div>
  <div class="cartela round">
    <%= f.text_area :content, placeholder: "cole o conteúdo da origem aqui", class: "round field_info" %>
  </div>    
  <div class= "update">
      <%= submit_tag "pronto", alt: "atualizar", class: "but round" %>
  </div>
  <div class= "update_">
    <% if @origin.author_id.blank? %>
      <% if current_user?(@origin.user)  %>
        <%= link_to "apagar fonte", @origin, 
                                                :class => "but round",
                                                :method => :delete, 
                                                :confirm => "têm certeza que deseja remover esta origem permanentemente?",
                                                :title => "apagar origem?" %>
      <% end %>
    <% else %>
      <%= link_to "voltar", @origin, class: "but round", title: "voltar para a página de #{@origin.name}" %> 
    <% end %>
  </div>
<% end %>

app/views/origins/_origin.html.erb
<div class= "origin_card">
  <div class= "origin_card_avatar">
    <%= link_to image_tag(origin.image_url, alt: origin.name), origin %>
  </div>
  <div class= "origin_card_info">
    <div class= "origin_card_name relative">
      <%= link_to origin.name, origin %>
      <% if origin.author.present? %>
        { <%= origin.author.name %><br />
      <% else %>
        { <%= origin.user.name %><br />
      <% end %>
      <div class= "origin_type">
        <% if origin.type? %>
          <% if origin.class == Book %>
            <%= image_tag "book.png" %><br />
          <% end %>
          <% if origin.class == Poem %>
            <%= image_tag "poem.png" %><br />
          <% end %>
          <% if origin.class == Song %>
            <%= image_tag "song.png" %><br />
          <% end %>
          <% if origin.class == Film %>
            <%= image_tag "film.png" %><br />
          <% end %>
          <% if origin.class == Other %>
            <%= image_tag "other.png" %><br />
          <% end %>
        <% end %>
      </div>
    </div>
    <!-- <div class= "stats">
      <p class= "p_stats">raspas</p>
      <%#= link_to (image_tag "ico_raspas.png"), origin,  :alt => "raspas", :class => "ico round" %>
      <%#= link_to origin.microposts.count, origin, :class => "but round", 
      title: "ver raspas de #{origin.name}" %>
    </div> -->
  </div>
</div>

app/views/origins/_origin_content.html.erb
<div class="origins round shadow">
  <div class= "origin">
    <div class= "origin_text">
      <div class= "origin_upwards">
        <%= simple_format (origin.content).html_safe %>
      </div>
    </div>
    <div class="quote_author">
      <%= image_tag "ico_raspas.png", alt: "raspa por" %>
      <% if !origin.author %>
        <%= link_to origin.user.name, origin.user %>
      <% else %>
        <%= link_to origin.author.name, origin.author %>
      <% end %>  
    </div>
    <div class= "tooltip">
      <% if !origin.author %>
        <%= render origin.user %>
      <% else %>  
        <%= render origin.author %>
      <% end %>
    </div>
    <div class="timestamp">
      <div class= "timestamp_each">
        <%= image_tag "clock_ico.png", title: "tempo no ar", alt: "há" %>
        <%= origin.created_at.strftime("%d.%m.%Y") %>
      </div>
      <% if origin.author %>
        <div class= "timestamp_each">  
          <div class= "quote_poster">
            <%= image_tag "raspa_ico.png", class: "raspa", title: "raspa de #{origin.user.name}", alt: "raspa de" %>
            <%= link_to origin.user.name, origin.user %>
          </div>
        </div>
        <div class= "tooltip">
          <%= render origin.user %>
        </div>
      <% end %>
      <% if !origin.tags.empty? %>
        <div class= "timestamp_each">
          <% origin.tags.each do |tag| %>
            <%= link_to (image_tag "tag_ico.png", alt: "sobre"), tag, title: "ver + raspas sobre #{tag.name}"  %>
            <%= link_to tag.name, tag, title: "ver + raspas sobre #{tag.name}" %>
          <% end %>
        </div>
      <% end %>
      <%# if !origin.published? %>
      <!--<div class= "timestamp_each"> 
          sob <%#= link_to "análise", @author %>
          <%#= link_to (image_tag "flag_ico.png"), root_path %>
        </div> -->
      <%# end %>
<!--       <%# if current_user?(origin.user) %>
        <div class= "timestamp_each">
          <%#= link_to (image_tag "edit.png", alt: "editar"), edit_origin_path(origin) %>
          <%#= link_to "editar", edit_origin_path(origin) %>
          <%#= link_to (image_tag "trash_ico.png", alt: "remover"), origin, :method => :delete,
                                           :confirm => "apagar esta raspa?",
                                           :title => "descartar" %>
          <%#= link_to "apagar", origin, :method => :delete,
                                           :confirm => "apagar este conteúdo?",
                                           :title => "descartar" %>

        </div>
      <%# end %> -->
    </div>
  </div>
</div>

app/views/origins/_origin_info.html.erb
<div class= "user_info">
  <div class= "user_avatar">
    <%= link_to (image_tag @origin.image_url(:profile).to_s, alt: @origin.name), edit_origin_path %>
  </div>
  <div class= "user_info">
    <div class= "user_info_board round">
      <div class= "name_edit">
        <p><%= @origin.name %></p>
        <% if @origin.author_id.blank? %>
          <% if current_user?(@origin.user)  %>
            <%= link_to (image_tag "edit.png", alt: "editar"), edit_origin_path %>
          <% end %>
        <% else %>
            <%= link_to (image_tag "edit.png", alt: "editar"), edit_origin_path %>
        <% end %>
      </div>
      <% if @origin.date? %>
        <%= @origin.date.strftime("%d.%m.%Y") %><br />
      <% end %>
      <div class= "origin_info_type">
        <% if @origin.type? %>
          <% if @origin.class == Book %>
            <%= image_tag "book.png", alt: 'livro' %><br />
          <% end %>
          <% if @origin.class == Poem %>
            <%= image_tag "poem.png", alt: 'poema' %><br />
          <% end %>
          <% if @origin.class == Song %>
            <%= image_tag "song.png", alt: 'música' %><br />
          <% end %>
          <% if @origin.class == Film %>
            <%= image_tag "film.png", alt: 'filme' %><br />
          <% end %>
          <% if @origin.class == Other %>
            <%= image_tag "other.png", alt: 'outros' %><br />
          <% end %>
        <% end %>
      </div>
    </div>
    <% if @origin.author %>
      <div class= "user_info_board round">
        <div class= "last_header">
          <p class="p_tags">do</p><p class="p_tag">pensador</p>
          <p class= "p_mais"><%= link_to "+", authors_path, title: "explorar pensadores" %></p>
        </div>
        <div class= "last">
          <div class= "last_users">
            <%= link_to image_tag(@origin.author.image_url(:tiny)), @origin.author, title: "ver perfil de #{@origin.author.name}" %>
            <div class= "last_upwards"> 
              <p><%= link_to @origin.author.name, @origin.author, title: "ver perfil de #{@origin.author.name}" %></p>
            </div>
          </div>
        </div>
      </div>
    <% else %>
      <div class= "user_info_board round">
        <div class= "last_header">
          <p class="p_tags">do</p><p class="p_tag">usuário</p>
          <p class= "p_mais"><%= link_to "+", users_path, title: "explorar usuários" %></p>
        </div>
        <div class= "last">
          <div class= "last_users">
            <%= link_to image_tag(@origin.user.image_url(:tiny), alt: @origin.user.name), @origin.user, title: "ver perfil de #{@origin.user.name}" %>
            <div class= "last_upwards"> 
                <p><%= link_to @origin.user.name, @origin.user, title: "ver perfil de #{@origin.user.name}" %></p>
            </div>
          </div>    
        </div>
      </div>
    <% end %>
    <% if !@tags.empty? %>
      <div class= "user_info_board round">
        <div class= "last_header">
          <p class="p_tag">temas</p><p class= "p_tags">abordados</p>
          <p class= "p_mais"><%= link_to "+", tags_path, title: "explorar temas" %></p>
        </div>
        <div>
          <% @tags.shuffle.first(20).each do |tag| %>
            <div>
              <%= link_to tag.name, tag, 
              title: "ver + raspas sobre #{tag.name}", :class => "but round temas" %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
    <% if @origin.info? %>
      <div class= "user_info_board round" >
        <div class= "bio">
          <%= auto_link(@origin.info, :all, target: '_blank').html_safe %>
        </div>
      </div>
      <% if @origin_user %>
        <div class= "user_info_board bio_poster round" >
          <div class= "bio">
            informações por<br /><%= link_to @origin_user.name, @origin_user if @origin_user %>
          </div>
        </div>
        <div class= "tooltip">
          <%= render @origin.user %>
        </div>
      <% end %>
    <% end %>
    <% if @origin.author && !@users.empty? %>
      <div class= "user_info_board round">
        <div class= "last_header">
          <p class="p_tag">citado</p><p class= "p_tags">pelos</p><p class="p_tag">usuários</p>
          <p class= "p_mais"><%= link_to "+", users_origin_path(@origin), title: "ver todos os usuários que já citaram #{@origin.name}" %></p>
        </div>
        <div>
          <% @users.shuffle.first(4).each do |user| %>
            <div class= "last">
              <div class= "last_users">
                <%= link_to image_tag(user.image_url(:tiny), alt: user.name), user, title: "ver perfil de #{user.name}" %>
                <div class= "last_upwards">
                  <p><%= link_to user.name, user, title: "ver perfil de #{user.name}" %></p>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
    <% if @author %>
      <% if @author_origins.count >= 2 %>  
        <div class= "user_info_board round">
          <div class= "last_header">
            <p class= "p_tag">outras</p><p class="p_tags">do</p><p class= "p_tag">pensador</p>
            <p class= "p_mais"><%= link_to "+", origins_author_path(@author), title: "explorar + materiais" %></p>
          </div>
          <div>
            <% @author_origins.shuffle.first(4).each do |origin| %>
              <div class= "last">
                <div class= "last_users">
                  <%= link_to image_tag(origin.image_url(:tiny), alt: origin.name), origin, title: "ver perfil de #{origin.name}" %>
                  <div class= "last_upwards">
                    <p><%= link_to origin.name, origin, title: "ver perfil de #{origin.name}" %></p>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>    
    <% else %>
      <% if @user_origins.count >= 2 %>  
        <div class= "user_info_board round">
          <div class= "last_header">
            <p class="p_tags">usuário</p><p class= "p_tag">citou</p><p class="p_tags">também</p>
            <p class= "p_mais"><%= link_to "+", origins_user_path(@user), title: "explorar + materiais" %></p>
          </div>
          <div>
            <% @user_origins.shuffle.first(4).each do |origin| %>
              <div class= "last">
                <div class= "last_users">
                  <%= link_to image_tag(origin.image_url(:tiny), alt: origin.name), origin, title: "ver perfil de #{origin.name}" %>
                  <div class= "last_upwards">
                    <p><%= link_to origin.name, origin, title: "ver perfil de #{origin.name}" %></p>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>  
    <% if @origin.class == Book %>
      <div class= "user_info_board round">
        <div class= "last_header">
          <p class= "p_tags">outras</p><p class="p_tag">livros</p>
          <p class= "p_mais"><%= link_to "+", books_path, title: "explorar livros" %></p>
        </div>
        <div>
          <% @books.shuffle.first(4).each do |book| %>
            <div class= "last">
              <div class= "last_users">
                <%= link_to image_tag(book.image_url(:tiny), alt: book.name), book, title: "ver perfil de #{book.name}" %>
                <div class= "last_upwards">
                  <p><%= link_to book.name, book, title: "ver perfil de #{book.name}" %></p>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>  
    <% end %>
    <% if @origin.class == Song %>
      <div class= "user_info_board round">
        <div class= "last_header">
          <p class= "p_tags">outras</p><p class="p_tag">músicas</p>
          <p class= "p_mais"><%= link_to "+", songs_path, title: "explorar músicas" %></p>
        </div>
        <div>
          <% @songs.shuffle.first(4).each do |song| %>
            <div class= "last">
              <div class= "last_users">
                <%= link_to image_tag(song.image_url(:tiny), alt: song.name), song, title: "ver perfil de #{song.name}" %>
                <div class= "last_upwards">
                  <p><%= link_to song.name, song, title: "ver perfil de #{song.name}" %></p>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>  
    <% end %>
    <% if @origin.class == Poem %>
      <div class= "user_info_board round">
        <div class= "last_header">
          <p class= "p_tags">outros</p><p class="p_tag">poemas</p>
          <p class= "p_mais"><%= link_to "+", poems_path, title: "explorar poemas" %></p>
        </div>
        <div>
          <% @poems.shuffle.first(4).each do |poem| %>
            <div class= "last">
              <div class= "last_users">
                <%= link_to image_tag(poem.image_url(:tiny), alt: poem.name), poem, title: "ver perfil de #{poem.name}" %>
                <div class= "last_upwards">
                  <p><%= link_to poem.name, poem, title: "ver perfil de #{poem.name}" %></p>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>  
    <% end %>
    <% if @origin.class == Film %>
      <div class= "user_info_board round">
        <div class= "last_header">
          <p class= "p_tags">outros</p><p class="p_tag">filmes</p>
          <p class= "p_mais"><%= link_to "+", films_path, title: "explorar músicas" %></p>
        </div>
        <div>
          <% @films.shuffle.first(4).each do |film| %>
            <div class= "last">
              <div class= "last_users">
                <%= link_to image_tag(film.image_url(:tiny), alt: film.name), film, title: "ver perfil de #{film.name}" %>
                <div class= "last_upwards">
                  <p><%= link_to film.name, film, title: "ver perfil de #{film.name}" %></p>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>  
    <% end %>
    <div class= "user_info_board round">
      <div class= "last_header">
        <p class= "p_tags">outras</p><p class="p_tag">origens</p>
        <p class= "p_mais"><%= link_to "+", origins_path, title: "explorar origens" %></p>
      </div>
      <div>
        <% @origins.shuffle.first(4).each do |origin| %>
          <div class= "last">
            <div class= "last_users">
              <%= link_to image_tag(origin.image_url(:tiny), alt: origin.name), origin, title: "ver perfil de #{origin.name}" %>
              <div class= "last_upwards">
                <p><%= link_to origin.name, origin, title: "ver perfil de #{origin.name}" %></p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/origins/edit.html.erb
<% if signed_in? %>
  <div class="home">  
    <%= render "form" %>
  </div> 
<% end %>

app/views/origins/index.html.erb
<div class= "home">
  <div class= "title">
    <p class= "p_search">explorando entre <%= Origin.count %> origens</p>
    <%= link_to "poemas", poems_path, class: text_active?('poems', 'index') %> 
    <%= link_to "filmes |", films_path, class: text_active?('films', 'index') %> 
    <%= link_to "livros |", books_path, class: text_active?('books', 'index') %> 
    <%= link_to "músicas |", songs_path, class: text_active?('songs', 'index') %> 
    <%= link_to "todas |", origins_path, class: text_active?('origins', 'index') %> 
  </div>
  <div id= "mason">
    <%= render @origins %>
  </div>
</div>
<div class= "pagination_square">
  <%= will_paginate @origins %>
</div>

app/views/origins/new.html.erb
<%= render 'form' %>

app/views/origins/show.html.erb
<div class="raspas"> 
  <div class="user_info">
    <%= render 'origin_info' %>
  </div>
  <div class="stack">
    <%# if @origin %>
      <%# unless @origin.published? %>
        <!-- <div class="half_quotes round">
          <div class= "sign">
            O perfil de <%#= @origin.name %> é recente e está sob análise.<br />
            Não gosta do que está vendo? Marque como abusivo!
          </div>
          <div class= "flag_sign">
            <%#= link_to (image_tag "flag_sign.png"), @origin %>
          </div>
        </div> -->
      <%# end %> 
    <%# end %>
    <% if signed_in? %>
      <% if @origin.image.blank? %>
        <div class="half_quotes round">
          <div class= "sign">
            Dica: adicione a capa de <%= @origin.name %>!<br />
            Edite esta origem pela engrenagem ao lado do nome.
          </div>
          <div class= "flag_sign">
            <%= image_tag "happy.png" %>
          </div>
        </div>
      <% end %>
    <% else %>
      <div class ="welcome_space"></div>
      <%= render 'shared/welcome' %>
    <% end %>
    <div>
      <% if !@microposts.empty? %>
        <%= render @microposts %>
        <%= will_paginate @microposts %>
      <% end %>
      <% if !@origin.link.blank? %>
        <div class= "origins round sahdow">
          <div class= "videos">
            <iframe width="560" height="350" src="<%= (@origin.link).html_safe %>" frameborder="0" allowfullscreen></iframe>
          </div>  
        </div> 
      <% end %>
      <% if !@origin.content.blank? %>
        <%= render 'origin_content', origin: @origin %>  
      <% end %>
    </div>
  </div>
</div>

app/views/origins/show_users.html.erb
<div class= "title">
  <p class= "p_search"><%= @origin.name %> foi citado por <%= pluralize @users.count, "usuário" %></p><%= link_to "explorar + usuários", users_path %>
</div>
<div class= "home">
  <ul class="users">
    <%= render @users %>
  </ul>
</div>