config/routes.rb
Benfeitor::Application.routes.draw do
  # scope :constraints => lambda{|request| request.cookies.key?("remember_token") } do
  #   root :to => "users#feed"
  # end    

  root :to => "pages#home"

  resources :authors, :path => "pensadores" do
    member do
      get :fans, path: "fas"
      get :idols, path: "idolos"
      get :users, path: "usuarios"
      get :tags, path: "temas"
      get :favourites, path: "favoritas"
      get :origins, path: "origens"
      get :books, path: "livros"
      get :songs, path: "musicas"
      get :poems, path: "poemas"
      get :films, path: "filmes"
      get :others, path: "outras"
      get :subscriptions, :autocomplete
    end
  end

  resources :users, path: "usuarios" do
    member do
      get :feed, path: "mural"
      get :following, path: "seguindo"
      get :followers, path: "seguidores"
      get :idols, path: "idolos"
      get :fans, path: "fas"
      get :tags, path: "temas"
      get :authors, path: "pensadores"
      get :favourites, path: "favoritas"
      get :origins, path: "origens"
      get :books, path: "livros"
      get :songs, path: "musicas"
      get :poems, path: "poemas"
      get :films, path: "filmes"
      get :others, path: "outras"
      get :favoritadas
      get :proprias
      get :twitter
    end
  end

  resources :tags, path: "temas" do
    member do
      get :microposts, path: "raspas"
      get :users, path: "usuarios"
      get :authors, path: "pensadores"
      get :autocomplete
    end
  end

  resources :taggins do
    member do
      get :tags, path: "temas"
      get :microposts, path: "raspas"
      get :users, path: "usuarios"
    end
  end

  resources :microposts, path: "raspas" do
    member do
      get :favouriters, path: "favoritaram"
    end
  end

  resources :favourites, path: "favoritas" do
    member do
      get :criar
    end
  end

  resources :origins, path: "origens" do

    member do
      get :fans, path: "fas"
      get :idols, path: "idolos"
      get :users, path: "usuarios"
      get :authors, path: "pensadores"
      get :tags, path: "temas"
      get :autocomplete
    end
  end

  resources :books, path: "livros"
  resources :poems, path: "poemas"
  resources :songs, path: "musicas"
  resources :films, path: "filmes"
  resources :others, path: "outras"
  
  resources :sessions, only: [:new, :create, :authenticate, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :subscriptions, only: [:create, :destroy]
  
  get '/signup',  to: 'users#new'
  get '/signin',  to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy'
  get '/home',   to: 'pages#home'
  get '/about',   to: 'pages#about'
  get 'contact' => 'contact#new'
  post 'contact' => 'contact#create'
  get '/auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get '/search', to: "search#index"
  get '/mosaico', to: "pages#mosaico"
  get '/top', to: "pages#top"
  get '/random', to: "microposts#random"
end

app/models/favourite.rb
class Favourite < ActiveRecord::Base
  	attr_accessible :micropost_id, :author_id, :poster_id, :user_id

	belongs_to :user
	belongs_to :author
	belongs_to :micropost, touch: true
	belongs_to :poster, class_name: "User"
	
end

app/controllers/favourites_controller.rb
# encoding: utf-8
class FavouritesController < ApplicationController 

	 def criar
    original_micropost = Micropost.find(params[:id])
    @micropost = Micropost.find(params[:id])
	 	# original_micropost = Micropost.find(params[:favourite][:micropost_id])
    if original_micropost
      if original_micropost.author
        favourite_micropost = current_user.favourites.build(micropost_id: original_micropost.id, author_id: original_micropost.author.id, poster_id: original_micropost.user.id)
      else
        favourite_micropost = current_user.favourites.build(micropost_id: original_micropost.id, poster_id: original_micropost.user.id)
      end
      respond_to do |format|
        format.html { redirect_to :back }
        format.js { @micropost }
      end
      if favourite_micropost.save
        # redirect_to :back#favourites_user_path(current_user)
        # flash[:success] = "Raspa adicionada às suas favoritas!"   
        unless original_micropost.user.email.blank?
          NotificationsMailer.favourite_notice(favourite_micropost).deliver
        end
      else
        redirect_to user_path(current_user), notice: new_micropost.errors.full_messages
      end
    else
      redirect_back_or current_user
      flash[:error] = "A raspa mencionada não existe mais!"
    end
  end

	def destroy
		@favourite = Favourite.find(params[:id])
    @micropost = @favourite.micropost
    @favourite.destroy
    # redirect_to favourites_user_path(current_user)
		# flash[:success] = "Raspa removida de suas favoritas!"
		respond_to do |format|
      format.html { redirect_to :back }
      format.js { @micropost }
    end
	end
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/views/favourites/_favo.html.erb
<div class= 'relative'>
	<%= link_to (image_tag "heart.png", alt: "favoritar"), criar_favourite_path(micropost), class: "top_button round wait_favo", title: "adicionar às favoritas", remote: true %>
</div>
<%= render 'shared/favo_count', micropost: micropost %>
<!--
<%#= form_for micropost.favourites.build(micropost_id: micropost.id) do |f| %>
  <div>
    <%#= f.hidden_field :micropost_id %>
  </div>
  <div>
    <%#= image_submit_tag "heart.png", alt: "favoritar", class: "favo_but round", title: "adicionar às favoritas" %>
  </div>
<%# end %>
-->

app/views/favourites/_favo_form.html.erb
<% if signed_in? %>
	<%= div_for micropost do %>
		<% if micropost.favourites.find_by_user_id(current_user) %>
		  <%= render 'favourites/unfavo', micropost: micropost %>
		<% else %>
		  <%= render 'favourites/favo', micropost: micropost %>
		<% end %>
	<% end %>
<% else %>
	<div>
		<%= link_to (image_tag "heart.png"), signin_path, class: "top_button round wait_favo" %>
		<%= render 'shared/favo_count', micropost: micropost %>
	</div>
<% end %>

app/views/favourites/_favourite.html.erb
<div class= "feed_quotes">
  <div class= "user_info">
    <% if favourite.micropost.author %>
      <%= link_to image_tag(favourite.micropost.author.image_url(:regular)), favourite.micropost.author, title: "ver perfil de #{favourite.micropost.author.name}" %>
    <% else %>  
      <%= link_to image_tag(favourite.micropost.user.image_url(:regular)), favourite.micropost.user, title: "ver perfil de #{favourite.micropost.user.name}" %>
    <% end %>
  </div>
  <div class= "stack_feed">
    <div class="quotes round shadow">
      <div class= "quote">
        <div class= "quote_text">
          <div class= "upwards">
            <% if !favourite.micropost.author %>
              <%= (favourite.micropost.content).html_safe %>
            <% else %>
              &quot;<%= (favourite.micropost.content).html_safe %>&quot;
            <% end %>
          </div>
        </div>
        <div class="quote_author">
          <%= image_tag "ico_raspas.png", alt: "raspa por" %>
          <% if !favourite.micropost.author %>
            <%= link_to favourite.micropost.user.name, favourite.micropost.user %>
          <% else %>
            <%= link_to favourite.micropost.author.name, favourite.micropost.author %>
          <% end %>
        </div>
        <div class= "tooltip">
          <% if !favourite.micropost.author %>
            <%= render favourite.micropost.user %>
          <% else %>  
            <%= render favourite.micropost.author %>
          <% end %>
        </div>
        <div class="timestamp">
          <div class= "timestamp_each">
            <%= image_tag "clock_ico.png", title: "tempo no ar" %>
            <%= favourite.micropost.created_at.strftime("%d.%m.%Y") %>
          </div>
          <% if favourite.micropost.author %>
            <div class= "timestamp_each">
              <div class= "quote_poster">
                <%= image_tag "raspa_ico.png", class: "raspa", title: "raspa de #{favourite.micropost.user.name}" %>
                <%= link_to favourite.micropost.user.name, favourite.micropost.user %>
              </div>
            </div>
            <div class= "tooltip">
              <%= render favourite.micropost.user %>
            </div>
          <% end %>
          <% if !favourite.micropost.tags.empty? %>
            <div class= "timestamp_each">
              <% favourite.micropost.tags.each do |tag| %>
              <%= link_to (image_tag "tag_ico.png"), tag, title: "ver + raspas sobre #{tag.name}"  %>
                <%= link_to tag.name, tag, title: "ver + raspas sobre #{tag.name}" %>
              <% end %>      
            </div>
          <% end %>
          <% if favourite.micropost.origin %>
            <div class= "timestamp_each">
              <div class= "quote_origin">
                <%= link_to (image_tag "other_ico.png", alt: "sobre"), favourite.micropost.origin, title: "ver + raspas de #{favourite.micropost.origin_id}" if favourite.micropost.origin.class.blank? %>
                <%= link_to (image_tag "book_ico.png", alt: "sobre"), favourite.micropost.origin, title: "ver + raspas de #{favourite.micropost.origin_id}" if favourite.micropost.origin.class == Book %>
                <%= link_to (image_tag "poem_ico.png", alt: "sobre"), favourite.micropost.origin, title: "ver + raspas de #{favourite.micropost.origin_id}" if favourite.micropost.origin.class == Poem %>
                <%= link_to (image_tag "song_ico.png", alt: "sobre"), favourite.micropost.origin, title: "ver + raspas de #{favourite.micropost.origin_id}" if favourite.micropost.origin.class == Song %>
                <%= link_to (image_tag "film_ico.png", alt: "sobre"), favourite.micropost.origin, title: "ver + raspas de #{favourite.micropost.origin_id}" if favourite.micropost.origin.class == Film %>
                <%= link_to (image_tag "other_ico.png", alt: "sobre"), favourite.micropost.origin, title: "ver + raspas de #{favourite.micropost.origin_id}" if favourite.micropost.origin.class == Other %>
                <%= link_to favourite.micropost.origin.name, favourite.micropost.origin %>
              </div>
            </div>
            <div class= "tooltip">
              <%= render favourite.micropost.origin %>
            </div>  
          <% end %>
          <% if favourite.micropost.favouriters.any? %>
            <div class= "timestamp_each">
              <% favourite.micropost.favouriters.first(1).each do |favouriters| %>
                <%= link_to (image_tag "heart_ico.png"), favouriters %>
                <%= link_to favouriters.name, favouriters, class: "quote_favouriters" %> 
                <div class= "tooltip">
                  <%= render favouriters %>
                </div>
                <% unless favourite.micropost.favouriters.count == 1 %>
                  + <%= link_to pluralize(favourite.micropost.favouriters.count - 1, "outro"), favouriters_micropost_path(favourite.micropost), title: "ver usuários que favoritaram esta raspa" %>
                <% end %>
              <% end %>
            </div>
          <% end %>
          <%# if !favourite.micropost.published? %>
            <!--<div class= "timestamp_each">
              sob <%#= link_to "análise", @author %> 
              <%#= link_to (image_tag "flag_ico.png"), root_path %>
            </div>-->
          <%# end %>
          <% if current_user?(favourite.micropost.user) %>
            <div class= "timestamp_each">
              <%= link_to (image_tag "edit.png"), edit_micropost_path(favourite.micropost) %>
              <%= link_to "editar", edit_micropost_path(favourite.micropost) %>
              <%= link_to (image_tag "trash_ico.png"), favourite.micropost, :method => :delete,
                                               :confirm => "apagar esta raspa?",
                                               :title => "descartar" %>
              <%= link_to "apagar", favourite.micropost, :method => :delete,
                                                 :confirm => "apagar esta raspa?",
                                                 :title => "descartar" %>             
            </div>
          <% end %>
        </div>
      </div>
      <div class= "quote_corner">
        <div class= "top_corner">
          <div>   
            <%= render 'favourites/favo_form', micropost: favourite.micropost %>
          </div> 
          <div class= "share">
            <% unless @micropost %>  
              <%= link_to (image_tag "share.png"), micropost_path(favourite.micropost), title: "compartilhar via facebook, twitter ou google+.", class: "top_button round" %>
            <% else %>
              <%= render "microposts/social" %>
            <% end %>
            <% if !@micropost %>
              <div class= "but_stats round">
                <p>compartilhar</p>
              </div>
            <% end %>
          </div>
        </div>
        <% if favourite.micropost.author %>
          <div class= "quote_poster_pic">
            <%= link_to image_tag(favourite.micropost.user.image_url(:small)), favourite.micropost.user %>
          </div>
        <% end %>
        <div class= "tooltip">
          <%= render favourite.micropost.user %>
        </div>
      </div>
    </div>
  </div>
</div>    

app/views/favourites/_unfavo.html.erb
<%= form_for micropost.favourites.find_by_user_id(current_user),
html: { method: :delete },
remote: true do |f| %>
  <div>
    <%= image_submit_tag "heart_broken.png", :class => "round", title: "descartar favorita" %>
  </div>
<% end %>
<%= render 'shared/favo_count', micropost: micropost %>

app/views/favourites/criar.js.erb
$("#<%= dom_id @micropost %>").html("<%=j render 'favourites/unfavo', micropost: @micropost %>")

app/views/favourites/destroy.js.erb
$("#<%= dom_id @micropost %>").html("<%=j render 'favourites/favo', micropost: @micropost %>")

app/views/favourites/unfavo.js.erb
gon.micropost.content