config/routes.rb
Benfeitor::Application.routes.draw do
  # scope :constraints => lambda{|request| request.cookies.key?("remember_token") } do
  #   root :to => "users#feed"
  # end    

  root :to => "pages#home"

  resources :authors, :path => "pensadores" do
    member do
      get :fans, path: "fas"
      get :idols, path: "idolos"
      get :users, path: "usuarios"
      get :tags, path: "temas"
      get :favourites, path: "favoritas"
      get :origins, path: "origens"
      get :books, path: "livros"
      get :songs, path: "musicas"
      get :poems, path: "poemas"
      get :films, path: "filmes"
      get :others, path: "outras"
      get :subscriptions, :autocomplete
    end
  end

  resources :users, path: "usuarios" do
    member do
      get :feed, path: "mural"
      get :following, path: "seguindo"
      get :followers, path: "seguidores"
      get :idols, path: "idolos"
      get :fans, path: "fas"
      get :tags, path: "temas"
      get :authors, path: "pensadores"
      get :favourites, path: "favoritas"
      get :origins, path: "origens"
      get :books, path: "livros"
      get :songs, path: "musicas"
      get :poems, path: "poemas"
      get :films, path: "filmes"
      get :others, path: "outras"
      get :favoritadas
      get :proprias
      get :twitter
    end
  end

  resources :tags, path: "temas" do
    member do
      get :microposts, path: "raspas"
      get :users, path: "usuarios"
      get :authors, path: "pensadores"
      get :autocomplete
    end
  end

  resources :taggins do
    member do
      get :tags, path: "temas"
      get :microposts, path: "raspas"
      get :users, path: "usuarios"
    end
  end

  resources :microposts, path: "raspas" do
    member do
      get :favouriters, path: "favoritaram"
    end
  end

  resources :favourites, path: "favoritas" do
    member do
      get :criar
    end
  end

  resources :origins, path: "origens" do

    member do
      get :fans, path: "fas"
      get :idols, path: "idolos"
      get :users, path: "usuarios"
      get :authors, path: "pensadores"
      get :tags, path: "temas"
      get :autocomplete
    end
  end

  resources :books, path: "livros"
  resources :poems, path: "poemas"
  resources :songs, path: "musicas"
  resources :films, path: "filmes"
  resources :others, path: "outras"
  
  resources :sessions, only: [:new, :create, :authenticate, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :subscriptions, only: [:create, :destroy]
  
  get '/signup',  to: 'users#new'
  get '/signin',  to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy'
  get '/home',   to: 'pages#home'
  get '/about',   to: 'pages#about'
  get 'contact' => 'contact#new'
  post 'contact' => 'contact#create'
  get '/auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get '/search', to: "search#index"
  get '/mosaico', to: "pages#mosaico"
  get '/top', to: "pages#top"
  get '/random', to: "microposts#random"
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  attr_accessible :content, :tag_names, :author_id, :author_name, :origin_name, :origin_id, :origin_type, :user_id
  
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  has_many :favourites, dependent: :destroy
  has_many :favouriters, through: :favourites, source: :user

  belongs_to :user
  belongs_to :author
  belongs_to :origin

  validates :content, presence: true, length: { maximum: 345 }, 
                                  uniqueness: { :case_sensitive => false }

  validates :user_id, presence: true

  scope :PUBLISHED, where(published: true)
  scope :UNPUBLISHED, where(published: false)

  scope :recent, order("microposts.created_at DESC")
  
  # Return microposts from the users being followed by the given user.
  scope :from_users_followed_by, lambda { |user| followed_by(user).recent }
  scope :from_authors_idols_of, lambda { |user| idols_of(user).recent }
  scope :from_microposts_favourites_of, lambda { |micropost| favourites_of(micropost).recent }
  scope :user_feed, lambda { |user| from_users_followed_by(user).concat(from_authors_idols_of(user)).concat(from_microposts_favourites_of(user)).uniq }

  attr_accessor :author_name, :origin_name, :origin_type
  attr_writer :tag_names, :author_name, :origin_name, :origin_type
  before_validation :normalize
  before_save :assign_author, :assign_origin
  after_save :assign_tags 

  def normalize
    if content
      self.content = content.gsub('"', '').gsub("'", '`').gsub("\r\n", ' ')
    end  
  end

  def favourites?(micropost)
    favourites.find_by_micropost_id(micropost)
  end

  def tag_names
    @tag_names || tags.map(&:name).join(',')
  end

  private

    def self.followed_by(user)
      following_ids = %(SELECT followed_id FROM relationships
                            WHERE follower_id = :user_id)
      where("user_id IN (#{following_ids}) OR user_id = :user_id",
            { user_id: user })
    end 

    def self.idols_of(user)
      idols_ids = %(SELECT author_id FROM subscriptions
                            WHERE user_id = :user_id)
      where("author_id IN (#{idols_ids}) OR user_id = :user_id",
            { user_id: user })
    end

    def self.favourites_of(user)
      eleitas_ids = %(SELECT micropost_id FROM favourites
                            WHERE user_id = :user_id)
      where("id IN (#{eleitas_ids}) OR user_id = :user_id",
            { user_id: user })
    end
  
    def assign_tags
      if @tag_names
        self.tags = @tag_names.gsub(', ', ',').split(',').map do |name|
          Tag.find_or_create_by_name(name.downcase)    
        end
      end   
    end

    def assign_author
      if author_name
        @some_author = Author.find_or_create_by_name(author_name)
        self.author_id = @some_author ? @some_author.id : 0
      end
    end

    def assign_origin
      if origin_name
        origin = Origin.find_or_create_by_name(origin_name)
        if origin
          if origin.user_id.blank?
            origin.update_attributes(user_id: user.id)
          end
          if !origin_type.blank?
            origin.update_attributes(type: origin_type)
          else
            if origin.type.blank?
              origin.update_attributes(type: 'Other')
            end
          end  
          if !author_name.blank?
            origin.update_attributes(author_id: @some_author.id)
          end
        end
        self.origin_id = origin ? origin.id : 0
      end
    end

    include PgSearch
    pg_search_scope :search, against: :content,
    using: {tsearch: {dictionary: "portuguese"}},
    associated_against: {author: :name, user: :name, tags: :name, origin: :name},
    ignoring: :accents  

    def self.text_search(query)
      if query.present?
        search(query)
      else
        scoped
      end
    end
end

app/controllers/microposts_controller.rb
# encoding: utf-8
class MicropostsController < ApplicationController
  before_filter :authenticate, only: [:create, :destroy, :favourites, :edit]
  before_filter :authorized_user, only: [:edit, :update, :destroy]

  def index
    @title = "Pensamentos e Frases"
    @microposts = Micropost.paginate(page: params[:page], order: "microposts.created_at DESC")
    @new_micropost = Micropost.new
    @authors = Author.all
    @tags = Tag.all
  end

  def show
    @micropost = Micropost.find(params[:id])
    @new_micropost = Micropost.new
    @tags = @micropost.tags
    @title = @micropost.content  
  end

  def create
    micropost = current_user.microposts.build(params[:micropost])
    if micropost.save
      if micropost.author
        redirect_to micropost.author
        flash[:success] = "Você adicionou um pensamento de #{micropost.author.name}! Obrigado."
      else
        redirect_back_or proprias_user_path(current_user)
        flash[:success] = "Adoramos ver raspas de sua própria autoria! Obrigado."
      end
    else
      content = micropost.content
      old_micropost = Micropost.find(:all, conditions: ['content LIKE ?', "#{content}"])
      if old_micropost
        redirect_to micropost_path(old_micropost)
        flash[:error] = "Ops! Sua raspa é repetida...favorite-a abaixo para guardá-la!"
      else
        redirect_to root_path
        flash[:error] = "Ops! Algo deu errado...parece que já temos esta raspa."
      end
    end
  end

  def edit
    @micropost = Micropost.find(params[:id])
    @title = "editar raspa"
    @new_micropost = Micropost.new
  end

  def update
    @micropost = Micropost.find(params[:id])
    @new_micropost = Micropost.new
    if @micropost.update_attributes(params[:micropost])
      flash[:success] = "Raspa atualizada com sucesso!"
      redirect_to @micropost.user
    else
      @title = "editar raspa"
      render 'edit'
    end
  end

  def destroy
    @micropost.destroy
    redirect_to current_user
  end

  def favouriters
    @title = "favoritaram"
    @micropost = Micropost.find(params[:id])
    @favouriters = @micropost.favouriters.paginate(:page => params[:page])
    @new_micropost = Micropost.new
    render 'show_favouriters'
  end

  def random
    @random = Micropost.offset(rand(Micropost.count)).first
    redirect_to @random
  end

  private

    def authorized_user
      @micropost = current_user.microposts.find_by_id(params[:id])
      redirect_to root_path if @micropost.nil?
    end
end

app/helpers/microposts_helper.rb
module MicropostsHelper

  def wrap(content)
    sanitize(raw(content.split.map{ |s| wrap_long_string(s) }.join(' ')))
  end

  private

    def wrap_long_string(text, max_width = 30)
      zero_width_space = "&#8203;"
      regex = /.{1,#{max_width}}/
      (text.length < max_width) ? text : 
                                  text.scan(regex).join(zero_width_space)
    end
end

app/views/microposts/_form.html.erb
<%= form_for @micropost do |f| %>
  <%= render 'shared/error_messages', object: f.object %>  
  <div class= "user_bar">
    <% @user ||= current_user %>
    <div class= "board_avatar">
      <%= link_to image_tag(@user.image_url(:regular)), current_user %>
    </div>
    <div class= "user_board">
      <%= f.text_area :content, maxlength: 345, placeholder: "escreva aqui sua raspa", title: "escreva uma raspa aqui" %>
      <div class= "count_micropost">
        <div id= "count">345</div>
      </div>
      <%= f.text_field :author_name, autofocus: true, value: "#{@micropost.author.name if @micropost.author}", data: {autocomplete_source: autocomplete_author_path(current_user)}, placeholder: "pensador", title: "caso esta frase seja sua, deixe o campo em branco" %>
        <%= f.text_field :tag_names, data: {autocomplete_source: autocomplete_tag_path(current_user)}, placeholder: "temas", title: "separe temas por vírgulas" %>
        <%= f.text_field :origin_name, value: "#{@micropost.origin.name if @micropost.origin}", data: {autocomplete_source: autocomplete_origin_path(current_user)}, placeholder: "origem", title: "livro, música, filme..." %>
      <%= image_submit_tag "raspa_.png", class: "write round" %>
    </div>
  </div>
<% end %>

app/views/microposts/_micropost.html.erb
<div class="quotes round shadow"> 
  <div class= "quote">
    <div class= "quote_text">
      <div class= "upwards">
        <% if !micropost.author %>
          <%= (micropost.content).html_safe %>
        <% else %>
          &quot;<%= (micropost.content).html_safe %>&quot;
        <% end %>
      </div>
    </div>
    <div class="quote_author">
      <%= image_tag "ico_raspas.png", alt: "raspa por" %>
      <% if !micropost.author %>
        <%= link_to micropost.user.name, micropost.user %>
      <% else %>
        <%= link_to micropost.author.name, micropost.author %>
      <% end %>  
    </div>
    <div class= "tooltip">
      <% if !micropost.author %>
        <%= render micropost.user %>
      <% else %>  
        <%= render micropost.author %>
      <% end %>
    </div>
    <div class="timestamp">
      <div class= "timestamp_each">
        <%= image_tag "clock_ico.png", title: "tempo no ar", alt: "há" %>
        <%= micropost.created_at.strftime("%d.%m.%Y") %>
      </div>
      <% if micropost.author %>
        <div class= "timestamp_each">  
          <div class= "quote_poster">
            <%= image_tag "raspa_ico.png", class: "raspa", title: "raspa de #{micropost.user.name}", alt: "raspa de" %>
            <%= link_to micropost.user.name, micropost.user %>
          </div>
        </div>
        <div class= "tooltip">
          <%= render micropost.user %>
        </div>
      <% end %>
      <% if !micropost.tags.empty? %>
        <div class= "timestamp_each">
          <% micropost.tags.each do |tag| %>
            <%= link_to (image_tag "tag_ico.png", alt: "sobre"), tag, title: "ver + raspas sobre #{tag.name}"  %>
            <%= link_to tag.name, tag, title: "ver + raspas sobre #{tag.name}" %>
          <% end %>
        </div>
      <% end %>
      <% if micropost.origin %>
        <div class= "timestamp_each">
          <div class= "quote_origin">
            <%= link_to (image_tag "other_ico.png", alt: "sobre"), micropost.origin, title: "ver + raspas de #{micropost.origin_id}" if micropost.origin.class.blank? %>
            <%= link_to (image_tag "book_ico.png", alt: "sobre"), micropost.origin, title: "ver + raspas de #{micropost.origin_id}" if micropost.origin.class == Book %>
            <%= link_to (image_tag "poem_ico.png", alt: "sobre"), micropost.origin, title: "ver + raspas de #{micropost.origin_id}" if micropost.origin.class == Poem %>
            <%= link_to (image_tag "song_ico.png", alt: "sobre"), micropost.origin, title: "ver + raspas de #{micropost.origin_id}" if micropost.origin.class == Song %>
            <%= link_to (image_tag "film_ico.png", alt: "sobre"), micropost.origin, title: "ver + raspas de #{micropost.origin_id}" if micropost.origin.class == Film %>
            <%= link_to (image_tag "other_ico.png", alt: "sobre"), micropost.origin, title: "ver + raspas de #{micropost.origin_id}" if micropost.origin.class == Other %>
            <%= link_to micropost.origin.name, micropost.origin %>
          </div>
        </div>
        <div class= "tooltip">
          <%= render micropost.origin %>
        </div>  
      <% end %>
      <% if micropost.favouriters.any? %>
        <div class= "timestamp_each">
          <% micropost.favouriters.first(1).each do |favouriters| %>
            <%= link_to (image_tag "heart_ico.png", alt: "favoritaram"), favouriters %>
            <%= link_to favouriters.name, favouriters, class: "quote_favouriters" %> 
            <div class= "tooltip">
              <%= render favouriters %>
            </div>
            <% unless micropost.favouriters.count == 1 %>
              + <%= link_to pluralize(micropost.favouriters.count - 1, "outro"), favouriters_micropost_path(micropost), title: "ver usuários que favoritaram esta raspa" %>
            <% end %>
          <% end %>
        </div>
      <% end %>
      <%# if !micropost.published? %>
      <!--<div class= "timestamp_each"> 
          sob <%#= link_to "análise", @author %>
          <%#= link_to (image_tag "flag_ico.png"), root_path %>
        </div> -->
      <%# end %>
      <% if current_user?(micropost.user) %>
        <div class= "timestamp_each">
          <%= link_to (image_tag "edit.png", alt: "editar"), edit_micropost_path(micropost) %>
          <%= link_to "editar", edit_micropost_path(micropost) %>
          <%= link_to (image_tag "trash_ico.png", alt: "remover"), micropost, :method => :delete,
                                           :confirm => "apagar esta raspa?",
                                           :title => "descartar" %>
          <%= link_to "apagar", micropost, :method => :delete,
                                           :confirm => "apagar esta raspa?",
                                           :title => "descartar" %>

        </div>
      <% end %>
    </div>
  </div>
  <div class= "quote_corner">
    <div class= "top_corner">
      <div>   
        <%= render 'favourites/favo_form', micropost: micropost %>
      </div>    
      <div class= "share">
        <% unless @micropost %>  
          <%= link_to (image_tag "share.png", alt: "compartilhar"), micropost_path(micropost), title: "compartilhar via facebook, twitter ou google+.", class: "top_button round" %>
          <div class= "but_stats round">
            <p>compartilhar</p>
          </div>
        <% else %>
          <%= render "microposts/social" %>
        <% end %>
      </div>
    </div>
    <div class= "quote_poster_pic">
      <%= link_to image_tag(micropost.user.image_url(:small)), micropost.user %>
    </div>
    <div class= "tooltip">
      <%= render micropost.user %>
    </div>
  </div>
</div>

app/views/microposts/_micropost_explorer.html.erb
<div class= "user_info">
	<div class= "logo_avatar round shadow">
		<%= link_to (image_tag "half_logo_.png"), root_path %>
	</div>
	<div class= "show_info">
		<div class= "user_info_board round">
			<p class="p_tag">explorando</p><p class="p_tags"><%= Micropost.count %></p><p class="p_tag">raspas</p>
		</div>
		<div class= "user_info_board round">
			<div class= "last_header">
				<p class="p_tag">filtre</p><p class="p_tags">por</p><p class="p_tag">temas</p>
				<p class= "p_mais"><%= link_to "+", tags_path, title: "explorar + temas" %></p>
			</div>
			<% @tags.shuffle.last(24).each do |tag| %>
			  <div>
			    <%= link_to tag.name, tag, :class => "but round temas", title: "ver raspas sobre #{tag.name}" %>
			  </div>
			<% end %>
		</div>
	</div>
</div>

app/views/microposts/_micropost_info.html.erb

<div class= "user_info">
	<div class= "user_avatar">
		<% if @micropost.author %>
			<%= link_to image_tag(@micropost.author.image_url(:regular), alt: @micropost.author.name), @micropost.author, title: "ver perfil de #{@micropost.author.name}" %>
		<% else %>
			<%= link_to image_tag(@micropost.user.image_url(:regular), alt: @micropost.user.name), @micropost.user, title: "ver perfil de #{@micropost.user.name}" %>
		<% end %>
	</div>
	<div class= "user_info_board round">
		<div class= "last_header">
			<p class="p_tag">raspa</p><p class="p_tags">#</p><p class="p_tag"><%= @micropost.id %></p>
			<p class= "p_mais"><%= link_to "+", microposts_path, title: "explorar + raspas" %></p>
		</div>
	</div>
	<% if @micropost.author %>
		<div class= "user_info_board round">
	        <div class= "last_header">
				<p class="p_tags">do</p><p class="p_tag">pensador</p>
	         	<p class= "p_mais"><%= link_to "+", authors_path, title: "explorar pensadores" %></p>
	        </div>
	        <div>
	            <div class= "last">
	              	<div class= "last_users">
	              		<%= link_to image_tag(@micropost.author.image_url(:tiny), alt: @micropost.author.name), @micropost.author, title: "ver perfil de #{@micropost.author.name}" %>
		            	<div class= "last_upwards">	
		              		<p><%= link_to @micropost.author.name, @micropost.author, title: "ver perfil de #{@micropost.author.name}" %></p>
		            	</div>
		            </div>
	            </div>    
	        </div>
	    </div>
	<% end %>
	<% if @micropost.origin %>
		<div class= "user_info_board round">
	        <div class= "last_header">
				<p class="p_tag">extraída</p><p class="p_tags">de</p>
	         	<p class= "p_mais"><%= link_to "+", origins_path, title: "explorar origens" %></p>
	        </div>
	        <div>
	            <div class= "last">
	              	<div class= "last_users">
	              		<%= link_to image_tag(@micropost.origin.image_url(:tiny), alt: @micropost.origin.name), @micropost.origin, title: "ver perfil de #{@micropost.origin.name}" %>
		            	<div class= "last_upwards">	
		              		<p><%= link_to @micropost.origin.name, @micropost.origin, title: "ver página de #{@micropost.origin.name}" %></p>
		            	</div>
		            </div>
	            </div>    
	        </div>
	    </div>
	<% end %>
	<div class= "user_info_board round">
        <div class= "last_header">
			<p class="p_tags">pelo</p><p class="p_tag">usuário</p>
        	<p class= "p_mais"><%= link_to "+", users_path, title: "explorar usuários" %></p>
        </div>
        <div>
            <div class= "last">
	          	<div class= "last_users">
	          		<%= link_to image_tag(@micropost.user.image_url(:tiny), alt: @micropost.user.name), @micropost.user, title: "ver perfil de #{@micropost.user.name}" %>
	          		<div class= "last_upwards">
              			<p><%= link_to @micropost.user.name, @micropost.user, title: "ver perfil de #{@micropost.user.name}" %></p>
           			</div>
       			</div>
       		</div>
        </div>
    </div>
	<% if !@tags.empty? %>
		<div class= "user_info_board round">
			<div class= "last_header">
				<p class="p_tag">sobre</p>
				<p class= "p_mais"><%= link_to "+", tags_path, title: "explorar + temas" %></p>
			</div>
			<div>
				<% @tags.each do |tag| %>
				  <div>
				    <%= link_to tag.name, tag, :class => "but round temas", title: "ver + raspas sobre #{tag.name}" %>
				  </div>
				<% end %>
			</div>
		</div>
	<% end %>
    <% if @micropost.favourites?(@micropost) %>
		<div class= "user_info_board round">
			<div class= "last_header">
				<p class="p_tag">favoritada</p><p class="p_tags"><%= @micropost.favourites.count %></p><p class="p_tag">x</p>
				<p class= "p_mais"><%= link_to "+", favouriters_micropost_path, title: "ver outros que favoritaram" %></p>
			</div>
			<div>
				<% @micropost.favourites.first(4).each do |favourite| %>
			        <div class= "last">
			            <div class= "last_users">
			            	<%= link_to image_tag(favourite.user.image_url(:tiny), alt: favourite.user.name), favourite.user, title: "ver perfil de #{favourite.user.name}" %>
                			<div class= "last_upwards">
			            		<p><%= link_to favourite.user.name, favourite.user, title: "ver perfil de #{favourite.user.name}" %></p>
			        		</div>
			        	</div>
			        </div>
		        <% end %>
			</div>
		</div>
	<% end %>
</div>

app/views/microposts/_social.html.erb
<!-- META TAGS for G+ SHARER -->

<meta property="og:title" content="<% if @micropost.author %><%= @micropost.author.name %><% else %><%= @micropost.user.name %><% end %>" />
<meta property="og:image" content="<% if @micropost.author %><%= @micropost.author.image %><% else %><%= @micropost.user.image %><% end %>" />
<meta property="og:description" content="'<%= @micropost.content %>'" />


<div class= "sharers">
  <div id='fb-root'></div>
  <script src='https://connect.facebook.net/pt_BR/all.js'></script>
  <p><a onclick='postToFeed(); return false;'><%= image_tag "fb_20.png", title: "compartilhar raspa no facebook" %></a></p>

  <!-- SCRIPT for FB FEED DIALOG -->

  <script>     
    function postToFeed() {

      // calling the API ...
      var obj = {
        method: 'feed',
        link: 'https://raspas.com.br/raspas/<%= @micropost.id %>',
        picture: '<% if @micropost.author %><% if !@micropost.author.image.blank? %><%= @micropost.author.image_url(:regular) %><% else %><%= image_tag "photos/default/medium_author.png" %><% end %><% else %><% if !@micropost.user.image.blank? %><%= @micropost.user.image_url(:regular) %><% else %><%= image_tag "photos/default/medium_user.png" %><% end %><% end %>',
        name: '"<%= h(@micropost.content) %>"',
        caption: '<% if @micropost.author %>{ <%= @micropost.author.name %><% else %>{ <%= @micropost.user.name %><% end %>',                                
        description: 'passe seu conhecimento adiante. crie, colecione e compartilhe pensamentos com o Raspas',  
      };

      function callback(response) {
        document.getElementById('msg').innerHTML = "compartido!";
      }

      FB.ui(obj, callback);
    }
  </script>
</div>

<div class= "sharers">  
  <g:plusone size="medium" annotation= "none"></g:plusone>
</div>  
<div class= "sharers">
  <a href="https://twitter.com/share" class="twitter-share-button" data-url="none" data-via="entre_raspas" data-related="entre_raspas" 
  data-text="'<%= @micropost.content %>'
  {  <% if @micropost.author %><%= @micropost.author.name %>

  <% else %><%= @micropost.user.name %>

  <% end %>" 
  data-lang="none" data-size="medium" data-related="entre_raspas" data-count="none" title="tweetar esta raspa"></a>
</div>
<div id= "msg"></div>

app/views/microposts/edit.html.erb
<% if signed_in? %>
  <div class="user_bar relative">  
    <%= render "form" %> 
  </div> 
<% end %>

app/views/microposts/index.html.erb
<div class= "home">
	<div class="user_info">
	 	<%= render 'micropost_explorer' %>
	</div>
	<div class="stack">
	    <% if !signed_in? %>
	      <div class ="welcome_space"></div>
	      <%= render 'shared/welcome' %>
	    <% end %>
	    <% unless @microposts.empty? %>
	      <%= render @microposts %>
	    <% end %>
	    <div class= "pagination_square">
			<%= will_paginate @microposts %>
		</div>
	</div>
</div>

app/views/microposts/show.html.erb
<div class="user_info">
	<%= render 'micropost_info' %>
</div>
<div class="stack">
	<% if !signed_in? %>
		<div class ="welcome_space"></div>
  		<%= render 'shared/welcome' %>
 	<% end %>
	<% if @micropost %>
		<%= render @micropost %>
		<div class= "absolute">
			<% if !signed_in? %>
				<div class ="welcome_space"></div>
			<% end %>
			<%= image_tag "compartilhar.png" %>
		</div>	
	<% end %>
</div>

app/views/microposts/show_favouriters.html.erb
<div class= "home">
	<div class= "title">
		<p class= "p_search">raspa marcada como favorita por <%= pluralize @favouriters.count, "usuário" %></p>
		<%= link_to "explorar outras raspas", microposts_path, title: "+ raspas" %>
	</div>
	<div class= "home_authors">
		<% @favouriters.each do |user| %>
            <div class= "home_authors_each">
			    <p><%= link_to user.name, user, title: "ver perfil de #{user.name}" %></p>
			    <%= link_to (image_tag user.image_url(:medium)), user, title: "ver perfil de #{user.name}" %>
			</div>
		<% end %>
	</div>
    <%= will_paginate @favouriters %>
</div>